name: Jest Coverage Report

on:
  pull_request:
  push:

jobs:
  Jest_Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd backend && npm ci
      - uses: mattallty/jest-github-action@v1.0.3
        with:
          working-directory: "backend"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
